#!/usr/bin/env python3
"""
Automated Build Script for iApp M3UI F-Droid Store
Validates project files, packages iApp .iapp archive, builds Android APK binary via Gradle,
and generates SHA-256 build checksums.
"""

import os
import json
import zipfile
import hashlib
import re
import shutil
import subprocess
import sys
import xml.etree.ElementTree as ET

BUILD_DIR = "dist"
OUTPUT_IAPP = os.path.join(BUILD_DIR, "FDroid_M3_Store.iapp")

def validate_files():
    print("=== [1/4] Validating Source Files ===")

    # 1. Validate src/config.json
    config_path = "src/config.json"
    with open(config_path, "r", encoding="utf-8") as f:
        config = json.load(f)
    print(f" [✓] {config_path} valid JSON.")
    assert config["defaultRepo"]["fingerprint"] == "43238D512C1E5EB2D6569F4A3AFBF5523418B82E0A3ED1552770ABB9A9C9CCAB"

    # 2. Validate .iyu XML Layout files
    for root, dirs, files in os.walk("src/views"):
        for file in files:
            if file.endswith(".iyu"):
                filepath = os.path.join(root, file)
                with open(filepath, "r", encoding="utf-8") as f:
                    content = f.read()
                xml_part = re.sub(r'<code_iyu>.*?</code_iyu>', '', content, flags=re.DOTALL).strip()
                ET.fromstring(xml_part)
                print(f" [✓] {filepath} XML layout valid.")

    # 3. Validate .myu modules
    for myu in ["src/m3ui/m3ui.myu", "src/fdroid/fdroid.myu"]:
        assert os.path.exists(myu) and os.path.getsize(myu) > 100
        print(f" [✓] {myu} script module valid.")

def package_iapp():
    print("\n=== [2/4] Packaging iApp Release (.iapp) ===")
    os.makedirs(BUILD_DIR, exist_ok=True)

    with zipfile.ZipFile(OUTPUT_IAPP, "w", zipfile.ZIP_DEFLATED) as zipf:
        for root, dirs, files in os.walk("src"):
            for file in files:
                filepath = os.path.join(root, file)
                # Map src/views/*.iyu to iyu/ directory structure
                if "/views/" in filepath and file.endswith(".iyu"):
                    arcname = os.path.join("iyu", file)
                # Map src/fdroid/ and src/m3ui/ .myu files to myu/ directory
                elif file.endswith(".myu"):
                    arcname = os.path.join("myu", file)
                else:
                    arcname = os.path.join("res", os.path.relpath(filepath, "src"))

                zipf.write(filepath, arcname)
                print(f" Added: {filepath} -> {arcname}")

    print(f" Successfully packaged iApp project: {OUTPUT_IAPP}")

def build_apk():
    print("\n=== [3/4] Building Android APK (Gradle) ===")

    # Sync src/ assets into app/src/main/assets/ for native iApp container
    assets_dir = os.path.join("app", "src", "main", "assets")
    os.makedirs(assets_dir, exist_ok=True)
    shutil.copy("src/config.json", os.path.join(assets_dir, "config.json"))

    cmd = "./gradlew assembleRelease --no-daemon" if os.name != 'nt' else "gradlew.bat assembleRelease --no-daemon"
    res = subprocess.run(cmd, shell=True, text=True)
    if res.returncode != 0:
        print("Gradle assembleRelease failed, retrying assembleDebug...")
        cmd_debug = "./gradlew assembleDebug --no-daemon" if os.name != 'nt' else "gradlew.bat assembleDebug --no-daemon"
        res_debug = subprocess.run(cmd_debug, shell=True, text=True)
        if res_debug.returncode != 0:
            print("ERROR: Gradle build failed!")
            sys.exit(1)

    apk_release = "app/build/outputs/apk/release/app-release-unsigned.apk"
    apk_debug = "app/build/outputs/apk/debug/app-debug.apk"

    target_apk = os.path.join(BUILD_DIR, "FDroid_M3_Store.apk")
    if os.path.exists(apk_release):
        shutil.copy(apk_release, target_apk)
        print(f" Compiled Release APK: {target_apk}")
    elif os.path.exists(apk_debug):
        shutil.copy(apk_debug, target_apk)
        print(f" Compiled Debug APK: {target_apk}")
    else:
        print("ERROR: No output APK artifact generated by Gradle!")
        sys.exit(1)

def generate_checksum():
    print("\n=== [4/4] Generating Build Checksums ===")
    sha256 = hashlib.sha256()
    with open(OUTPUT_IAPP, "rb") as f:
        while chunk := f.read(8192):
            sha256.update(chunk)
    iapp_digest = sha256.hexdigest().upper()
    print(f" File: {OUTPUT_IAPP} | SHA-256: {iapp_digest}")

    checksum_lines = [f"{iapp_digest}  FDroid_M3_Store.iapp"]

    target_apk = os.path.join(BUILD_DIR, "FDroid_M3_Store.apk")
    if os.path.exists(target_apk):
        sha_apk = hashlib.sha256()
        with open(target_apk, "rb") as f:
            while chunk := f.read(8192):
                sha_apk.update(chunk)
        apk_digest = sha_apk.hexdigest().upper()
        print(f" File: {target_apk} | SHA-256: {apk_digest}")
        checksum_lines.append(f"{apk_digest}  FDroid_M3_Store.apk")

    with open(os.path.join(BUILD_DIR, "BUILD_SHA256.txt"), "w", encoding="utf-8") as f:
        f.write("\n".join(checksum_lines) + "\n")

if __name__ == "__main__":
    validate_files()
    package_iapp()
    build_apk()
    generate_checksum()
    print("\n Automated Build Completed Successfully!")
